<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config [
  <!ELEMENT config (output, colors*, security, textElemGroup, controlAuthorityGroup, frontMatterGroup, pmGroup, maintenance, company, comment)>

  <!ELEMENT output (method+,(layout?)+)>
  <!ELEMENT method (path+,pathCache)>
  <!ELEMENT path (#PCDATA)>
  <!ELEMENT pathCache (#PCDATA)>
  <!ELEMENT layout (simple-page-master)>
  <!ELEMENT colors (color+)>
  <!ELEMENT color EMPTY>
  
  <!ELEMENT simple-page-master (
    master-name_for_odd, margin-top_for_odd, margin-bottom_for_odd, margin-left_for_odd, margin-right_for_odd, margin-top_for_odd_body, margin-bottom_for_odd_body, margin-left_for_odd_body, margin-right_for_odd_body, extent_for_odd_header, extent_for_odd_footer,
    master-name_for_even, margin-top_for_even, margin-bottom_for_even, margin-left_for_even, margin-right_for_even, margin-top_for_even_body, margin-bottom_for_even_body, margin-left_for_even_body, margin-right_for_even_body, extent_for_even_header, extent_for_even_footer,
    master-name_for_leftBlank, margin-top_for_leftBlank, margin-bottom_for_leftBlank, margin-left_for_leftBlank, margin-right_for_leftBlank, margin-top_for_leftBlank_body, margin-bottom_for_leftBlank_body, margin-left_for_leftBlank_body, margin-right_for_leftBlank_body, extent_for_leftBlank_header, extent_for_leftBlank_footer,
    region-name_for_body, region-name_for_bodyLeftBlank, region-name_for_headerOdd, region-name_for_footerOdd, region-name_for_headerEven, region-name_for_footerEven, region-name_for_headerLeftBlank, region-name_for_footerLeftBlank
    )>
  <!-- odd -->
  <!ELEMENT master-name_for_odd (#PCDATA)>
  <!ELEMENT margin-top_for_odd (#PCDATA)>
  <!ELEMENT margin-bottom_for_odd (#PCDATA)>
  <!ELEMENT margin-left_for_odd (#PCDATA)>
  <!ELEMENT margin-right_for_odd (#PCDATA)>
  <!ELEMENT margin-top_for_odd_body (#PCDATA)>
  <!ELEMENT margin-bottom_for_odd_body (#PCDATA)>
  <!ELEMENT margin-left_for_odd_body (#PCDATA)>
  <!ELEMENT margin-right_for_odd_body (#PCDATA)>
  <!ELEMENT extent_for_odd_header (#PCDATA)>
  <!ELEMENT extent_for_odd_footer (#PCDATA)>
  <!-- even -->
  <!ELEMENT master-name_for_even (#PCDATA)>
  <!ELEMENT margin-top_for_even (#PCDATA)>
  <!ELEMENT margin-bottom_for_even (#PCDATA)>
  <!ELEMENT margin-left_for_even (#PCDATA)>
  <!ELEMENT margin-right_for_even (#PCDATA)>
  <!ELEMENT margin-top_for_even_body (#PCDATA)>
  <!ELEMENT margin-bottom_for_even_body (#PCDATA)>
  <!ELEMENT margin-left_for_even_body (#PCDATA)>
  <!ELEMENT margin-right_for_even_body (#PCDATA)>
  <!ELEMENT extent_for_even_header (#PCDATA)>
  <!ELEMENT extent_for_even_footer (#PCDATA)>
  <!-- left blank -->
  <!ELEMENT master-name_for_leftBlank (#PCDATA)>
  <!ELEMENT margin-top_for_leftBlank (#PCDATA)>
  <!ELEMENT margin-bottom_for_leftBlank (#PCDATA)>
  <!ELEMENT margin-left_for_leftBlank (#PCDATA)>
  <!ELEMENT margin-right_for_leftBlank (#PCDATA)>
  <!ELEMENT margin-top_for_leftBlank_body (#PCDATA)>
  <!ELEMENT margin-bottom_for_leftBlank_body (#PCDATA)>
  <!ELEMENT margin-left_for_leftBlank_body (#PCDATA)>
  <!ELEMENT margin-right_for_leftBlank_body (#PCDATA)>
  <!ELEMENT extent_for_leftBlank_header (#PCDATA)>
  <!ELEMENT extent_for_leftBlank_footer (#PCDATA)>
  <!-- region name -->
  <!ELEMENT region-name_for_body (#PCDATA)>
  <!ELEMENT region-name_for_bodyLeftBlank (#PCDATA)>
  <!ELEMENT region-name_for_headerOdd (#PCDATA)>
  <!ELEMENT region-name_for_footerOdd (#PCDATA)>
  <!ELEMENT region-name_for_headerEven (#PCDATA)>
  <!ELEMENT region-name_for_footerEven (#PCDATA)>
  <!ELEMENT region-name_for_headerLeftBlank (#PCDATA)>
  <!ELEMENT region-name_for_footerLeftBlank (#PCDATA)>

  <!ELEMENT security (securityClassification+,commercialClassification?,caveat?, derivativeClassification?)>
  <!ELEMENT securityClassification (#PCDATA)>
  <!ELEMENT commercialClassification (#PCDATA)>
  <!ELEMENT caveat (#PCDATA)>
  <!ELEMENT derivativeClassification (action+)>
  <!ELEMENT action (#PCDATA)>

  <!ELEMENT textElemGroup (emphasis|crewMember|crewStepCondition|skillType|skillLevelCode|caption|quantity|internalRef|verbatimText)*>
  <!ELEMENT emphasis (#PCDATA)>
  <!ELEMENT crewMember (#PCDATA)>
  <!ELEMENT crewStepCondition (#PCDATA)>
  <!ELEMENT skillType (#PCDATA)>
  <!ELEMENT skillLevelCode (#PCDATA)>
  <!ELEMENT caption (#PCDATA)>
  <!ELEMENT quantity (#PCDATA)>
  <!ELEMENT internalRef (#PCDATA)>
  <!ELEMENT verbatimText (#PCDATA)>
  
  <!ELEMENT controlAuthorityGroup (controlAuthority+)>
  <!ELEMENT controlAuthority (#PCDATA)>

  <!ELEMENT frontMatterGroup (frontMatter)*>
  <!ELEMENT frontMatter (#PCDATA)>

  <!ELEMENT pmGroup (pt|pmt)*>
  <!ELEMENT pt (#PCDATA)>
  <!ELEMENT pmt (#PCDATA)>

  <!ELEMENT maintenance (source|threshold|task)*>
  <!ELEMENT source (#PCDATA)>
  <!ELEMENT threshold (#PCDATA)>
  <!ELEMENT task (#PCDATA)>

  <!ELEMENT company (companyCode)*>
  <!ELEMENT companyCode (#PCDATA)>

  <!ELEMENT comment (commentPriority|commentResponse)*>
  <!ELEMENT commentPriority (#PCDATA)>
  <!ELEMENT commentResponse (#PCDATA)>

  <!ATTLIST method type (html|pdf) #REQUIRED>
  <!ATTLIST path product-name CDATA #REQUIRED>
  <!ATTLIST layout master-name CDATA #REQUIRED>
  <!ATTLIST layout length-unit CDATA #REQUIRED>
  <!ATTLIST layout area-unit CDATA #REQUIRED>
  <!ATTLIST layout height CDATA #REQUIRED>
  <!ATTLIST layout width CDATA #REQUIRED>
  <!ATTLIST layout default-font-size CDATA #IMPLIED>
  <!ATTLIST layout cgmark-offset CDATA #IMPLIED>
  <!ATTLIST layout start-indent CDATA #IMPLIED>
  <!ATTLIST layout orientation (port|land) #IMPLIED>
  <!ATTLIST source type CDATA #REQUIRED>
  <!ATTLIST threshold uom CDATA #REQUIRED>
  <!ATTLIST companyCode code CDATA #REQUIRED>
  <!ATTLIST commentPriority code CDATA #REQUIRED>
  <!ATTLIST commentResponse type CDATA #REQUIRED>

  <!-- <!ATTLIST layout width CDATA #REQUIRED>
  <!ATTLIST layout height CDATA #REQUIRED>
  <!ATTLIST layout region-before CDATA #REQUIRED>
  <!ATTLIST layout region-after CDATA #REQUIRED>
  <!ATTLIST layout start-indent CDATA #IMPLIED>
  <!ATTLIST layout cgmark-indent CDATA #IMPLIED>
  <!ATTLIST layout default-font-size CDATA #IMPLIED> -->

  <!-- <!ATTLIST layout margin-top CDATA #REQUIRED>
  <!ATTLIST layout margin-bottom CDATA #REQUIRED>
  <!ATTLIST layout margin-right CDATA #REQUIRED>
  <!ATTLIST layout margin-left CDATA #REQUIRED>
  <!ATTLIST layout orientation (port|land) #IMPLIED> -->

  <!ATTLIST colors mode (rgb|cmyk|hex) #REQUIRED>
  <!ATTLIST color name CDATA #REQUIRED>
  <!ATTLIST color code CDATA #REQUIRED>

  <!ATTLIST securityClassification code CDATA #REQUIRED>
  <!ATTLIST commercialClassification code CDATA #REQUIRED>
  <!ATTLIST caveat code CDATA #REQUIRED>
  <!ATTLIST action code CDATA #REQUIRED>

  <!ATTLIST emphasis type CDATA #REQUIRED>
  <!ATTLIST crewMember type CDATA #REQUIRED>
  <!ATTLIST crewStepCondition type CDATA #REQUIRED>
  <!ATTLIST skillType type CDATA #REQUIRED>
  <!ATTLIST skillLevelCode type CDATA #REQUIRED>
  <!ATTLIST caption type CDATA #REQUIRED>
  <!ATTLIST caption background-color CDATA #REQUIRED>
  <!ATTLIST caption color CDATA #REQUIRED>
  <!ATTLIST quantity type CDATA #REQUIRED>
  <!ATTLIST internalRef type CDATA #REQUIRED>
  <!ATTLIST verbatimText type CDATA #REQUIRED>

  <!ATTLIST controlAuthority type CDATA #REQUIRED>
  <!ATTLIST frontMatter type CDATA #REQUIRED>
  <!ATTLIST pt type CDATA #REQUIRED>
  <!ATTLIST pmt type CDATA #REQUIRED>
  <!ATTLIST task code CDATA #REQUIRED>
]>

<config>
  <output>
    <method type="html">
      <path product-name="*">html/Main.xsl</path>
      <pathCache></pathCache>
    </method>
    <method type="pdf">
      <path product-name="CN235">pdf/CN235/Main.xsl</path>
      <path product-name="CN235-220M">pdf/CN235/Main.xsl</path>
      <path product-name="MALE">pdf/MALE/Main.xsl</path>
      <pathCache>pdf/transformed/</pathCache>
    </method>
    <layout master-name="default-A4L" length-unit="cm" area-unit="pt" width="29.7" height="21" default-font-size="11" cgmark-offset="0.5cm" start-indent="1.5" orientation="land">
      <simple-page-master>
        <master-name_for_odd>odd</master-name_for_odd>
        <margin-top_for_odd>3</margin-top_for_odd>
        <margin-bottom_for_odd>1.5</margin-bottom_for_odd>
        <margin-left_for_odd>2</margin-left_for_odd>
        <margin-right_for_odd>1</margin-right_for_odd>
        <margin-top_for_odd_body>0</margin-top_for_odd_body>
        <margin-bottom_for_odd_body>0</margin-bottom_for_odd_body>
        <margin-left_for_odd_body>1</margin-left_for_odd_body>
        <margin-right_for_odd_body>1</margin-right_for_odd_body>
        <extent_for_odd_header>0.5</extent_for_odd_header>
        <extent_for_odd_footer>-1.5</extent_for_odd_footer>

        <master-name_for_even>even</master-name_for_even>
        <margin-top_for_even>1.5</margin-top_for_even>
        <margin-bottom_for_even>3</margin-bottom_for_even>
        <margin-left_for_even>2</margin-left_for_even>
        <margin-right_for_even>1</margin-right_for_even>
        <margin-top_for_even_body>0</margin-top_for_even_body>
        <margin-bottom_for_even_body>0</margin-bottom_for_even_body>
        <margin-left_for_even_body>1</margin-left_for_even_body>
        <margin-right_for_even_body>1</margin-right_for_even_body>
        <extent_for_even_header>0.5</extent_for_even_header>
        <extent_for_even_footer>-1.5</extent_for_even_footer>

        <master-name_for_leftBlank>left-blank</master-name_for_leftBlank>
        <margin-top_for_leftBlank>1</margin-top_for_leftBlank>
        <margin-bottom_for_leftBlank>1</margin-bottom_for_leftBlank>
        <margin-left_for_leftBlank>1.5</margin-left_for_leftBlank>
        <margin-right_for_leftBlank>3</margin-right_for_leftBlank>
        <margin-top_for_leftBlank_body>1.5</margin-top_for_leftBlank_body>
        <margin-bottom_for_leftBlank_body>2</margin-bottom_for_leftBlank_body>
        <margin-left_for_leftBlank_body>0</margin-left_for_leftBlank_body>
        <margin-right_for_leftBlank_body>0</margin-right_for_leftBlank_body>
        <extent_for_leftBlank_header>1.5</extent_for_leftBlank_header>
        <extent_for_leftBlank_footer>2</extent_for_leftBlank_footer>

        <region-name_for_body>body</region-name_for_body>
        <region-name_for_bodyLeftBlank>left_blank</region-name_for_bodyLeftBlank>
        <region-name_for_headerOdd>header-odd</region-name_for_headerOdd>
        <region-name_for_footerOdd>footer-odd</region-name_for_footerOdd>
        <region-name_for_headerEven>header-even</region-name_for_headerEven>
        <region-name_for_footerEven>footer-even</region-name_for_footerEven>
        <region-name_for_headerLeftBlank>header-left_blank</region-name_for_headerLeftBlank>
        <region-name_for_footerLeftBlank>footer-left_blank</region-name_for_footerLeftBlank>
      </simple-page-master>
    </layout>
    <layout master-name="default-A4" length-unit="cm" area-unit="pt" width="21" height="29.7" default-font-size="11" cgmark-offset="2cm" start-indent="1.5" orientation="port">
      <simple-page-master>
        <master-name_for_odd>odd</master-name_for_odd>
        <margin-top_for_odd>1</margin-top_for_odd>
        <margin-bottom_for_odd>1</margin-bottom_for_odd>
        <margin-left_for_odd>3</margin-left_for_odd>
        <margin-right_for_odd>1.5</margin-right_for_odd>
        <margin-top_for_odd_body>1.5</margin-top_for_odd_body>
        <margin-bottom_for_odd_body>1.7</margin-bottom_for_odd_body>
        <margin-left_for_odd_body>0</margin-left_for_odd_body>
        <margin-right_for_odd_body>0</margin-right_for_odd_body>
        <extent_for_odd_header>1.5</extent_for_odd_header>
        <extent_for_odd_footer>1.5</extent_for_odd_footer>

        <master-name_for_even>even</master-name_for_even>
        <margin-top_for_even>1</margin-top_for_even>
        <margin-bottom_for_even>1</margin-bottom_for_even>
        <margin-left_for_even>1.5</margin-left_for_even>
        <margin-right_for_even>3</margin-right_for_even>
        <margin-top_for_even_body>1.5</margin-top_for_even_body>
        <margin-bottom_for_even_body>1.7</margin-bottom_for_even_body>
        <margin-left_for_even_body>0</margin-left_for_even_body>
        <margin-right_for_even_body>0</margin-right_for_even_body>
        <extent_for_even_header>1.5</extent_for_even_header>
        <extent_for_even_footer>1.5</extent_for_even_footer>

        <master-name_for_leftBlank>left-blank</master-name_for_leftBlank>
        <margin-top_for_leftBlank>1</margin-top_for_leftBlank>
        <margin-bottom_for_leftBlank>1</margin-bottom_for_leftBlank>
        <margin-left_for_leftBlank>1.5</margin-left_for_leftBlank>
        <margin-right_for_leftBlank>3</margin-right_for_leftBlank>
        <margin-top_for_leftBlank_body>1.5</margin-top_for_leftBlank_body>
        <margin-bottom_for_leftBlank_body>2</margin-bottom_for_leftBlank_body>
        <margin-left_for_leftBlank_body>0</margin-left_for_leftBlank_body>
        <margin-right_for_leftBlank_body>0</margin-right_for_leftBlank_body>
        <extent_for_leftBlank_header>1.5</extent_for_leftBlank_header>
        <extent_for_leftBlank_footer>2</extent_for_leftBlank_footer>

        <region-name_for_body>body</region-name_for_body>
        <region-name_for_bodyLeftBlank>left_blank</region-name_for_bodyLeftBlank>
        <region-name_for_headerOdd>header-odd</region-name_for_headerOdd>
        <region-name_for_footerOdd>footer-odd</region-name_for_footerOdd>
        <region-name_for_headerEven>header-even</region-name_for_headerEven>
        <region-name_for_footerEven>footer-even</region-name_for_footerEven>
        <region-name_for_headerLeftBlank>header-left_blank</region-name_for_headerLeftBlank>
        <region-name_for_footerLeftBlank>footer-left_blank</region-name_for_footerLeftBlank>
      </simple-page-master>
    </layout>
    <layout master-name="default-pm" length-unit="cm" area-unit="pt" width="21" height="29.7" default-font-size="11" cgmark-offset="2cm" start-indent="1.5" orientation="port">
      <simple-page-master>
        <master-name_for_odd>oddA4</master-name_for_odd>
        <margin-top_for_odd>1</margin-top_for_odd>
        <margin-bottom_for_odd>1</margin-bottom_for_odd>
        <margin-left_for_odd>3</margin-left_for_odd>
        <margin-right_for_odd>1.5</margin-right_for_odd>
        <margin-top_for_odd_body>1.5</margin-top_for_odd_body>
        <margin-bottom_for_odd_body>1.7</margin-bottom_for_odd_body>
        <margin-left_for_odd_body>0</margin-left_for_odd_body>
        <margin-right_for_odd_body>0</margin-right_for_odd_body>
        <extent_for_odd_header>1.5</extent_for_odd_header>
        <extent_for_odd_footer>1.5</extent_for_odd_footer>

        <master-name_for_even>evenA4</master-name_for_even>
        <margin-top_for_even>1</margin-top_for_even>
        <margin-bottom_for_even>1</margin-bottom_for_even>
        <margin-left_for_even>1.5</margin-left_for_even>
        <margin-right_for_even>3</margin-right_for_even>
        <margin-top_for_even_body>1.5</margin-top_for_even_body>
        <margin-bottom_for_even_body>1.7</margin-bottom_for_even_body>
        <margin-left_for_even_body>0</margin-left_for_even_body>
        <margin-right_for_even_body>0</margin-right_for_even_body>
        <extent_for_even_header>1.5</extent_for_even_header>
        <extent_for_even_footer>1.5</extent_for_even_footer>

        <master-name_for_leftBlank>left-blankA4</master-name_for_leftBlank>
        <margin-top_for_leftBlank>1</margin-top_for_leftBlank>
        <margin-bottom_for_leftBlank>1</margin-bottom_for_leftBlank>
        <margin-left_for_leftBlank>1.5</margin-left_for_leftBlank>
        <margin-right_for_leftBlank>3</margin-right_for_leftBlank>
        <margin-top_for_leftBlank_body>1.5</margin-top_for_leftBlank_body>
        <margin-bottom_for_leftBlank_body>2</margin-bottom_for_leftBlank_body>
        <margin-left_for_leftBlank_body>0</margin-left_for_leftBlank_body>
        <margin-right_for_leftBlank_body>0</margin-right_for_leftBlank_body>
        <extent_for_leftBlank_header>1.5</extent_for_leftBlank_header>
        <extent_for_leftBlank_footer>2</extent_for_leftBlank_footer>

        <region-name_for_body>body</region-name_for_body>
        <region-name_for_bodyLeftBlank>left_blank</region-name_for_bodyLeftBlank>
        <region-name_for_headerOdd>header-odd</region-name_for_headerOdd>
        <region-name_for_footerOdd>footer-odd</region-name_for_footerOdd>
        <region-name_for_headerEven>header-even</region-name_for_headerEven>
        <region-name_for_footerEven>footer-even</region-name_for_footerEven>
        <region-name_for_headerLeftBlank>header-left_blank</region-name_for_headerLeftBlank>
        <region-name_for_footerLeftBlank>footer-left_blank</region-name_for_footerLeftBlank>
      </simple-page-master>
    </layout>
    <layout master-name="poh" length-unit="cm" area-unit="pt" width="14.8" height="21" default-font-size="10" cgmark-offset="2cm" start-indent="1.5" orientation="port">
      <simple-page-master>
        <master-name_for_odd>oddA5_poh</master-name_for_odd>
        <margin-top_for_odd>1</margin-top_for_odd>
        <margin-bottom_for_odd>1</margin-bottom_for_odd>
        <margin-left_for_odd>2</margin-left_for_odd>
        <margin-right_for_odd>1</margin-right_for_odd>
        <margin-top_for_odd_body>1.5</margin-top_for_odd_body>
        <margin-bottom_for_odd_body>1.2</margin-bottom_for_odd_body>
        <margin-left_for_odd_body>0</margin-left_for_odd_body>
        <margin-right_for_odd_body>0</margin-right_for_odd_body>
        <extent_for_odd_header>1.2</extent_for_odd_header>
        <extent_for_odd_footer>1.2</extent_for_odd_footer>

        <master-name_for_even>evenA4_poh</master-name_for_even>
        <margin-top_for_even>1</margin-top_for_even>
        <margin-bottom_for_even>1</margin-bottom_for_even>
        <margin-left_for_even>1</margin-left_for_even>
        <margin-right_for_even>2</margin-right_for_even>
        <margin-top_for_even_body>1.5</margin-top_for_even_body>
        <margin-bottom_for_even_body>1.2</margin-bottom_for_even_body>
        <margin-left_for_even_body>0</margin-left_for_even_body>
        <margin-right_for_even_body>0</margin-right_for_even_body>
        <extent_for_even_header>1.2</extent_for_even_header>
        <extent_for_even_footer>1.2</extent_for_even_footer>

        <master-name_for_leftBlank>left-blankA4_poh</master-name_for_leftBlank>
        <margin-top_for_leftBlank>1</margin-top_for_leftBlank>
        <margin-bottom_for_leftBlank>1</margin-bottom_for_leftBlank>
        <margin-left_for_leftBlank>1</margin-left_for_leftBlank>
        <margin-right_for_leftBlank>2</margin-right_for_leftBlank>
        <margin-top_for_leftBlank_body>1.2</margin-top_for_leftBlank_body>
        <margin-bottom_for_leftBlank_body>1.2</margin-bottom_for_leftBlank_body>
        <margin-left_for_leftBlank_body>0</margin-left_for_leftBlank_body>
        <margin-right_for_leftBlank_body>0</margin-right_for_leftBlank_body>
        <extent_for_leftBlank_header>1.2</extent_for_leftBlank_header>
        <extent_for_leftBlank_footer>1.2</extent_for_leftBlank_footer>

        <region-name_for_body>body</region-name_for_body>
        <region-name_for_bodyLeftBlank>left_blank</region-name_for_bodyLeftBlank>
        <region-name_for_headerOdd>header-odd</region-name_for_headerOdd>
        <region-name_for_footerOdd>footer-odd</region-name_for_footerOdd>
        <region-name_for_headerEven>header-even</region-name_for_headerEven>
        <region-name_for_footerEven>footer-even</region-name_for_footerEven>
        <region-name_for_headerLeftBlank>header-left_blank</region-name_for_headerLeftBlank>
        <region-name_for_footerLeftBlank>footer-left_blank</region-name_for_footerLeftBlank>
      </simple-page-master>
    </layout>
    <layout master-name="maintPlanning" length-unit="cm" area-unit="pt" width="29.7" height="21" default-font-size="11" cgmark-offset="0.5cm" start-indent="1.5" orientation="land">
      <simple-page-master>
        <master-name_for_odd>odd</master-name_for_odd>
        <margin-top_for_odd>3</margin-top_for_odd>
        <margin-bottom_for_odd>1.5</margin-bottom_for_odd>
        <margin-left_for_odd>2</margin-left_for_odd>
        <margin-right_for_odd>1</margin-right_for_odd>
        <margin-top_for_odd_body>0</margin-top_for_odd_body>
        <margin-bottom_for_odd_body>0</margin-bottom_for_odd_body>
        <margin-left_for_odd_body>1</margin-left_for_odd_body>
        <margin-right_for_odd_body>1</margin-right_for_odd_body>
        <extent_for_odd_header>0.5</extent_for_odd_header>
        <extent_for_odd_footer>-1.5</extent_for_odd_footer>

        <master-name_for_even>even</master-name_for_even>
        <margin-top_for_even>1.5</margin-top_for_even>
        <margin-bottom_for_even>3</margin-bottom_for_even>
        <margin-left_for_even>2</margin-left_for_even>
        <margin-right_for_even>1</margin-right_for_even>
        <margin-top_for_even_body>0</margin-top_for_even_body>
        <margin-bottom_for_even_body>0</margin-bottom_for_even_body>
        <margin-left_for_even_body>1</margin-left_for_even_body>
        <margin-right_for_even_body>1</margin-right_for_even_body>
        <extent_for_even_header>0.5</extent_for_even_header>
        <extent_for_even_footer>-1.5</extent_for_even_footer>

        <master-name_for_leftBlank>left-blank</master-name_for_leftBlank>
        <margin-top_for_leftBlank>1.5</margin-top_for_leftBlank>
        <margin-bottom_for_leftBlank>3</margin-bottom_for_leftBlank>
        <margin-left_for_leftBlank>2</margin-left_for_leftBlank>
        <margin-right_for_leftBlank>1</margin-right_for_leftBlank>
        <margin-top_for_leftBlank_body>0</margin-top_for_leftBlank_body>
        <margin-bottom_for_leftBlank_body>1</margin-bottom_for_leftBlank_body>
        <margin-left_for_leftBlank_body>1</margin-left_for_leftBlank_body>
        <margin-right_for_leftBlank_body>1</margin-right_for_leftBlank_body>
        <extent_for_leftBlank_header>0.5</extent_for_leftBlank_header>
        <extent_for_leftBlank_footer>-1.5</extent_for_leftBlank_footer>

        <region-name_for_body>body</region-name_for_body>
        <region-name_for_bodyLeftBlank>left_blank-maintPlanning</region-name_for_bodyLeftBlank>
        <region-name_for_headerOdd>header-odd-maintPlanning</region-name_for_headerOdd>
        <region-name_for_footerOdd>footer-odd-maintPlanning</region-name_for_footerOdd>
        <region-name_for_headerEven>header-even-maintPlanning</region-name_for_headerEven>
        <region-name_for_footerEven>footer-even-maintPlanning</region-name_for_footerEven>
        <region-name_for_headerLeftBlank>header-left_blank-maintPlanning</region-name_for_headerLeftBlank>
        <region-name_for_footerLeftBlank>footer-left_blank-maintPlanning</region-name_for_footerLeftBlank>
      </simple-page-master>
    </layout>
  </output>
  <colors mode="hex">
    <color name="amber" code="#ffc107"/>
    <color name="black" code="#00000"/>
    <color name="green" code="#14a339"/>
    <color name="grey" code="#808080"/>
    <color name="red" code="#ff0000"/>
    <color name="white" code="#ffffff"/>
    <color name="white" code="#ffff00"/>
  </colors>
  <security>
    <securityClassification code="01">UNCLASSIFIED</securityClassification>
    <securityClassification code="02">RESTRICTED</securityClassification>
    <securityClassification code="03">CONFIDENTIAL</securityClassification>
    <securityClassification code="04">SECRET</securityClassification>
    <securityClassification code="05">TOP SECRET</securityClassification>
    <commercialClassification code="cc51">FOOBAR CC</commercialClassification>
    <caveat code="cv51">FOO CAVEAT</caveat>
    <derivativeClassification>
      <action code="ai01">Classified On</action>
      <action code="ai02">Declasify On</action>
      <action code="ai03">Downgrande On</action>
      <action code="ai04">Upgrade On</action>
      <action code="ai05">Downgrade SC to 03</action>
      <action code="ai06">Downgrade SC to 04</action>
      <action code="ai07">Downgrade SC to 05</action>
      <action code="ai08">Upgrade SC to 03</action>
      <action code="ai09">Upgrade SC to 04</action>
      <action code="ai10">Upgrade SC to 05</action>
    </derivativeClassification>
  </security>
  <textElemGroup>
    <emphasis type="em01">bold</emphasis>
    <emphasis type="em02">italic</emphasis>
    <emphasis type="em03">underline</emphasis>
    <emphasis type="em05">strikethrough</emphasis>
    <emphasis type="em06">underline-bold</emphasis>
    <emphasis type="em07">underline-italic</emphasis>
    <emphasis type="em08">bold-italic</emphasis>
    <emphasis type="em09">bold-italic-underline</emphasis>
    <crewMember type="cm01">All</crewMember>
    <crewMember type="cm02">Pilot</crewMember>
    <crewMember type="cm03">Co-Pilot</crewMember>
    <crewMember type="cm04">Navigator</crewMember>
    <crewMember type="cm05">Engineer</crewMember>
    <crewMember type="cm06">Ground Crew</crewMember>
    <crewMember type="cm07">Load Master</crewMember>
    <crewMember type="cm08">Cabin Spv.</crewMember>
    <crewMember type="cm51">CM1</crewMember>
    <crewMember type="cm52">CM2</crewMember>
    <crewMember type="cm53">CM3</crewMember>
    <crewMember type="cm54">Pil1</crewMember>
    <crewMember type="cm55">Pil2</crewMember>
    <crewMember type="cm56">Pil3</crewMember>
    <crewMember type="cm57">Pil4</crewMember>
    <crewMember type="cm58">MO</crewMember>
    <crewMember type="cm59">LM</crewMember>
    <crewMember type="cm60">T</crewMember>
    <crewStepCondition type="csc01">Equipment is installed or available</crewStepCondition>
    <crewStepCondition type="csc02">A detailed procedure for the step is located in the performance section of the condensed checklists</crewStepCondition>
    <crewStepCondition type="csc03">Performance of the step is mandatory for all through-flights used for combat/tactical operations</crewStepCondition>
    <crewStepCondition type="csc04">A step that is mandatory for night flights</crewStepCondition>
    <crewStepCondition type="csc05">A task or step required by the operator's manual</crewStepCondition>
    <skillType type="st01">AIRPL</skillType>
    <skillType type="st02">ELEC</skillType>
    <skillType type="st03">AVION</skillType>
    <skillType type="st04">ENGIN</skillType>
    <skillLevelCode type="sk01">Basic</skillLevelCode>
    <skillLevelCode type="sk02">Intermediate</skillLevelCode>
    <skillLevelCode type="sk03">Advanced</skillLevelCode>
    <caption type="co01" background-color="green" color="black"/>
    <caption type="co02" background-color="amber" color="black"/>
    <caption type="co03" background-color="yellow" color="black"/>
    <caption type="co04" background-color="red" color="black"/>
    <caption type="co07" background-color="white" color="black"/>
    <caption type="co08" background-color="grey" color="black"/>
    <caption type="co62" background-color="yellow" color="white"/>
    <caption type="co66" background-color="red" color="black"/>
    <caption type="co67" background-color="red" color="white"/>
    <caption type="co81" background-color="black" color="yellow"/>
    <caption type="co82" background-color="black" color="white"/>
    <caption type="co83" background-color="black" color="red"/>
    <caption type="co84" background-color="black" color="green"/>
    <caption type="co85" background-color="black" color="amber"/>
    <quantity type="qty51">Panel CB CN235</quantity>
    <internalRef type="irtt01">figure</internalRef>
    <internalRef type="irtt02">table</internalRef>
    <internalRef type="irtt03">multimedia</internalRef>
    <internalRef type="irtt04">supply</internalRef>
    <internalRef type="irtt05">support Equipment</internalRef>
    <internalRef type="irtt06">spare</internalRef>
    <internalRef type="irtt07">para</internalRef>
    <internalRef type="irtt08">step</internalRef>
    <internalRef type="irtt09"></internalRef>
    <internalRef type="irtt10">multimedia</internalRef>
    <internalRef type="irtt11">zone</internalRef>
    <internalRef type="irtt14">work area</internalRef>
    <internalRef type="irtt15">SB</internalRef>
    <internalRef type="irtt16">access</internalRef>
    <verbatimText type="vs51">monospace</verbatimText>
    <verbatimText type="vs52">calibri</verbatimText>
  </textElemGroup>

  <controlAuthorityGroup>
    <controlAuthority type="cat01">AD</controlAuthority>    
    <controlAuthority type="cat02">AMOC</controlAuthority>    
    <controlAuthority type="cat03">AWL</controlAuthority>    
    <controlAuthority type="cat04">CATIII</controlAuthority>    
    <controlAuthority type="cat05">CDCCL</controlAuthority>    
    <controlAuthority type="cat06">CMR</controlAuthority>    
    <controlAuthority type="cat07">ETOPS</controlAuthority>    
    <controlAuthority type="cat08">EWIS</controlAuthority>    
    <controlAuthority type="cat09">LOI</controlAuthority>    
    <controlAuthority type="cat10">RII</controlAuthority>    
    <controlAuthority type="cat51">DGCA</controlAuthority>    
  </controlAuthorityGroup>

  <frontMatterGroup>
    <frontMatter type="fm01">leop</frontMatter>
    <frontMatter type="fm02">leodm</frontMatter>
    <frontMatter type="fm03">highlights</frontMatter>
    <frontMatter type="fm04">highlights and updating instruction</frontMatter>
    <frontMatter type="fm05">publication list data modules</frontMatter>
    <frontMatter type="fm06">loi</frontMatter>
    <frontMatter type="fm07">loa</frontMatter>
    <frontMatter type="fm08">lot</frontMatter>
    <frontMatter type="fm09">los</frontMatter>
    <frontMatter type="fm10">tsr</frontMatter>
    <frontMatter type="fm11">lom</frontMatter>
    <frontMatter type="fm12">loasd</frontMatter>
    <frontMatter type="fm13">low</frontMatter>
    <frontMatter type="fm14">loc</frontMatter>
    <frontMatter type="fm15">lose</frontMatter>
    <frontMatter type="fm16">losu</frontMatter>
    <frontMatter type="fm17">losp</frontMatter>